INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'AZUL',1);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'BAHIA BLANCA',1);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'CABA',2);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'FIAMBELA',3);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'LA PUERTA',3);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'MACHAGAI',4);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'PUERTO TIROL',4);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'JOSE DE SAN MARTIN',5);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'PUERTO MADRYN',5);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'BAILET MASSE',6);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'CASA GRANDE',6);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'MBURUCUYA',7);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'PASO DE LA PATRIA',7);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'GUALEGUAYCHU',8);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'IBICUY',8);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'CLORINDA',9);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'FORMOSA CAPITAL',9);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'VOLCAN',10);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'PURMAMARCA',10);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'INTENDENTE ALVEAR',11);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'RANCUL',11);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'SANAGASTA',12);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'TAMA',12);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'JUNIN',13);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'LAS HERAS',13);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'COLONIA',14);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'EL ALCAZAR',14);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'LAS LAJAS',15);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'EQUIS',15);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'LAS GRUTAS',16);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'PLAYAS DORADAS',16);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'JOAQUIN GONZALEZ',17);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'MOLINOS',17);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'SANTA LUCIA',18);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'VALLE FERTIL',18);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'LOS MOLLES',19);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'MOGOLI',19);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'PICO TRUNCADO',20);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'PUERTO SANTA CURZ',20);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'CHABAS',21);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'ELORTONDO',21);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'FRIAS',22);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'PINTO',22);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'RIO GRANDE',23);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'USHUAIA',23);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'SIMONACA',24);

INSERT INTO LOCALIDAD(ID_LOCALIDAD,NOMBRE_LOCALIDAD,ID_PROVINCIA)
VALUES(LOCALIDAD_SEQ.NEXTVAL,'ALBERDI',24);
