   insert into EXTRA(ID_EXTRA,FECHA,ID_POLIZA,ID_COBERTURA )
VALUES ( EXTRA_SEQ.NEXTVAL, '15072015' ,6  , 1);
insert into EXTRA(ID_EXTRA,FECHA,ID_POLIZA,ID_COBERTURA )
VALUES ( EXTRA_SEQ.NEXTVAL, '15072015' , 5, 4);
insert into EXTRA(ID_EXTRA,FECHA,ID_POLIZA,ID_COBERTURA )
VALUES ( EXTRA_SEQ.NEXTVAL, '15072015' , 5, 5);
insert into EXTRA(ID_EXTRA,FECHA,ID_POLIZA,ID_COBERTURA )
VALUES ( EXTRA_SEQ.NEXTVAL, '15072015' , 1, 5);
insert into EXTRA(ID_EXTRA,FECHA,ID_POLIZA,ID_COBERTURA )
VALUES ( EXTRA_SEQ.NEXTVAL, '15072015' , 1, 4);
