
INSERT INTO PRODUCTOR (ID_PRODUCTOR, RAZON_SOCIAL) VALUES (PRODUCTOR_SEQ.NEXTVAL, 'Pepito SA');
INSERT INTO PRODUCTOR (ID_PRODUCTOR, RAZON_SOCIAL) VALUES (PRODUCTOR_SEQ.NEXTVAL, 'Nico Seguros SRL');
INSERT INTO PRODUCTOR (ID_PRODUCTOR, RAZON_SOCIAL) VALUES (PRODUCTOR_SEQ.NEXTVAL, 'Seguros LP');
INSERT INTO PRODUCTOR (ID_PRODUCTOR, RAZON_SOCIAL) VALUES (PRODUCTOR_SEQ.NEXTVAL, 'AutoSeguros SA');
INSERT INTO PRODUCTOR (ID_PRODUCTOR, RAZON_SOCIAL) VALUES (PRODUCTOR_SEQ.NEXTVAL, 'Anda Tranquilo SA');
INSERT INTO PRODUCTOR (ID_PRODUCTOR, RAZON_SOCIAL) VALUES (PRODUCTOR_SEQ.NEXTVAL, 'Tu Aseguradora Amiga');