
insert into PORCENTAJE_COBERTURA(ID_PORCENTAJE,ID_COBERTURA,DESDE_FECHA,HASTA_FECHA,PORCENTAJE )
VALUES ( PORCENTAJE_COBERTURA_SEQ.NEXTVAL,1,'10102013',NULL,'15');


insert into PORCENTAJE_COBERTURA(ID_PORCENTAJE,ID_COBERTURA,DESDE_FECHA,HASTA_FECHA,PORCENTAJE )
VALUES ( PORCENTAJE_COBERTURA_SEQ.NEXTVAL,2,'10102013',NULL,'20');
insert into PORCENTAJE_COBERTURA(ID_PORCENTAJE,ID_COBERTURA,DESDE_FECHA,HASTA_FECHA,PORCENTAJE )
VALUES ( PORCENTAJE_COBERTURA_SEQ.NEXTVAL,3,'10122014',NULL,'05');
insert into PORCENTAJE_COBERTURA(ID_PORCENTAJE,ID_COBERTURA,DESDE_FECHA,HASTA_FECHA,PORCENTAJE )
VALUES ( PORCENTAJE_COBERTURA_SEQ.NEXTVAL,4,'01052015',NULL,'23');
insert into PORCENTAJE_COBERTURA(ID_PORCENTAJE,ID_COBERTURA,DESDE_FECHA,HASTA_FECHA,PORCENTAJE )
VALUES ( PORCENTAJE_COBERTURA_SEQ.NEXTVAL,5,'10112014',NULL,'20');
insert into PORCENTAJE_COBERTURA(ID_PORCENTAJE,ID_COBERTURA,DESDE_FECHA,HASTA_FECHA,PORCENTAJE )
VALUES ( PORCENTAJE_COBERTURA_SEQ.NEXTVAL,6,'12122012',NULL,'18');
 

