INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'A1', 1);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'A3', 1);

INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'I3', 2);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'I8', 2);

INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'VITARA', 3);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'VAN N200', 3);

INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'2015 CHRYSLER 300', 4);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'2015 CHRYSLER TOWN AND COUNTRY', 4);

INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'C3 Picasso', 5);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'C4 Lounge', 5);

INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Tacuma', 6);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Lacetti', 6);

INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'CALIBER', 7);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Challenger', 7);

INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Grand Siena Attractive 1.4', 8);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Palio Attractive', 8);

INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'EcoSport', 9);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Galaxy', 9);

INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Citan', 10);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Clase SLK', 10);

INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Land Cruiser Prado', 11);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Prius', 11);

INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Clio', 12);
INSERT INTO MODELO(ID_MODELO, NOMBRE_MODELO, ID_MARCA) VALUES (MODELO_SEQ.NEXTVAL,'Megane', 12);
