insert into plan(ID_PLAN,NOMBRE_PLAN,TIPO )
VALUES ( PLAN_SEQ.NEXTVAL,'BASICO','CERRADO');
insert into plan(ID_PLAN,NOMBRE_PLAN,TIPO )
VALUES ( PLAN_SEQ.NEXTVAL,'TODO RIESGO','CERRADO'), 
insert into plan(ID_PLAN,NOMBRE_PLAN,TIPO )
VALUES ( PLAN_SEQ.NEXTVAL,'PLAN 220','CERRADO'), 
insert into plan(ID_PLAN,NOMBRE_PLAN,TIPO )
VALUES ( PLAN_SEQ.NEXTVAL,'PLAN 360','CERRADO'), 
insert into plan(ID_PLAN,NOMBRE_PLAN,TIPO )
VALUES ( PLAN_SEQ.NEXTVAL,'TROTAMUNDOS','CERRADO'), 



