insert into COBERTURA(ID_COBERTURA,DESCRIPCION)
VALUES ( COBERTURA_SEQ.NEXTVAL,'GRANIZO');
insert into COBERTURA(ID_COBERTURA,DESCRIPCION)
VALUES( COBERTURA_SEQ.NEXTVAL,'TERCEROS');
insert into COBERTURA(ID_COBERTURA,DESCRIPCION)
VALUES( COBERTURA_SEQ.NEXTVAL,'ARBOLES');
insert into COBERTURA(ID_COBERTURA,DESCRIPCION)
VALUES( COBERTURA_SEQ.NEXTVAL,'INCENDIO');
insert into COBERTURA(ID_COBERTURA,DESCRIPCION)
VALUES( COBERTURA_SEQ.NEXTVAL,'ROBO');    
insert into COBERTURA(ID_COBERTURA,DESCRIPCION)
VALUES( COBERTURA_SEQ.NEXTVAL,'CHOQUE');    