 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 1,6);    
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 1,2);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 2,6);    
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 2,2);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 2,5);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 2,1);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 3,1);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 3,2);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 3,3);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 4,1);

 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 4,2);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 4,3);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 4,4);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 4,5);

 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 5,1);

 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 5,2);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 5,3);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 5,4);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 5,5);
 insert into REGISTRO_COBERTURA(ID_PLAN,ID_COBERTURA)
VALUES( 5,5);
 